---
title: "Heatwave"
output: html_document
date: "2025-08-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r import_packages, warning=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(purrr)
"%ni%" <- Negate("%in%")
library(googlesheets4)
library(patchwork)
library(growthrates)
```

## Ammonium trials

```{r}
ammonium_trial<-read_sheet("https://docs.google.com/spreadsheets/d/1QRzU9teNRcPwRhmw8oUkU11Vfzaa26bnVQpcDRTGL2E/edit?usp=sharing")

ammonium_trial$Date <- ymd(ammonium_trial$Date)
ammonium_trial$Rep <- as.character(ammonium_trial$Rep)
ammonium_trial$RFU <- as.numeric(ammonium_trial$RFU)
data(ammonium_trial)
str(ammonium_trial)
head(ammonium_trial)
```

```{r}
ammonium_trial %>% ggplot(aes(x = Day, y = RFU, color = Culture, shape = factor (Round)) ) +
  geom_point () +
  theme_test () +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_shape_manual(values = c(16,4,15,20,25)) +
  ggtitle(expression("Pyrodinium growth with " * NH[4]^"+" * " addition and " * NO[3]^"-" * " elimination")) +
  facet_grid(~ case_when(
    Round == 3 ~ "S.T. 1 (Round 3)",
    Round == 4 ~ "S.T. 2 (Round 4)",
    Round == 5 ~ "S.T. 3 (Round 5)",
    TRUE       ~ "Rounds 1 and 2"), scales = "free_x")
```
ggsave("ammoniumtrial_929.jpg", width = 10, height = 8)



```{r}
library(ggplot2)
library(dplyr)
ammonium_trial %>% filter(Round == "2") %>% ggplot(aes(x = Day, y = RFU, color = Culture, shape = factor (Round)) ) +
  geom_point () +
  theme_test () +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_shape_manual(values = c(4)) +
  ggtitle(expression("Pyrodinium growth with " * NH[4]^"+" * " addition and " * NO[3]^"-" * " elimination"))
```


```{r}
amm <- ammonium_trial %>% filter(Round %in% c(2)) %>% separate(Culture, into = c("bact"), sep = "_", remove = FALSE ) %>%
  separate(bact, into = c("x", "y", "z", "bact1"), sep = " ", remove = FALSE) %>% mutate(bact1 = case_when(bact %in% c("LL", "OTB") ~ bact, bact %ni% c("LL", "OTB") ~ bact1))

amm %>% ggplot(aes(x=Day, y = RFU, color = bact1)) + geom_point(alpha = 0.8) + theme_test() + facet_grid(~Round) + scale_color_manual(values = c("cornflowerblue", "gold" ))+ geom_smooth(se = FALSE) #+ scale_y_log10()
```
## Clean NH4
```{r}
"%ni%" <- Negate("%in%")

amm <- ammonium_trial %>% filter(Round %in% c(1, 3, 4, 5)) %>% separate(Culture, into = c("bact"), sep = "_", remove = FALSE ) %>%
  separate(bact, into = c("x", "y", "z", "bact1"), sep = " ", remove = FALSE) %>% mutate(bact1 = case_when(bact %in% c("LL", "OTB") ~ bact, bact %ni% c("LL", "OTB") ~ bact1))
 
amm %>% ggplot(aes(x=Day, y = RFU, color = bact1)) + geom_point(alpha = 0.8) + theme_test() + facet_grid(~Round) + scale_color_manual(values = c("cornflowerblue", "gold" ))+ geom_smooth(se = FALSE) #+ scale_y_log10()
```

ggsave("ammoniumtrialclean_1015.jpg", width = 10, height = 8)

```{r}

`%ni%` <- Negate(`%in%`)

#Function Definition
plot_by_day <- function(data = ammonium_trial, rounds = c(1, 3, 4, 5)) {
  
#Data
  amm <- data %>%
    filter(Round %in% rounds) %>%
    separate(Culture, into = c("bact"), sep = "_", remove = FALSE) %>%
    separate(bact, into = c("x", "y", "z", "bact1"), sep = " ", remove = FALSE) %>%
    mutate(
      bact1 = case_when(
        bact %in% c("LL", "OTB") ~ bact,
        bact %ni% c("LL", "OTB") ~ bact1
      )
    )
  
#Plot
  plot <- ggplot(amm, aes(x = Day, y = RFU, color = bact1)) +
    geom_point(alpha = 0.8) +
    geom_smooth(se = FALSE) +
    theme_test() +
    facet_grid(~Round) +
    scale_color_manual(values = c("cornflowerblue", "gold"))
    # + scale_y_log10() 
  
  return(plot)
}


```


## Growth rates for Round 1 LL
```{r}
library(ggplot2)
library(dplyr)
ammonium_trial %>% filter(Round == "1", Culture == "LL_1006 7/23" ) %>% ggplot(aes(x = Date, y = RFU, color = Culture, shape = factor (Round)) ) +
  geom_point () +
  theme_test () +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_shape_manual(values = c(16)) +
  ggtitle(expression("Pyrodinium growth with " * NH[4]^"+" * " addition and " * NO[3]^"-" * " elimination"))

```

```{r}
library(growthrates)
rnd1 <- ammonium_trial %>% filter(Round == "1", Culture == "LL_1006 7/23" ) %>%
  mutate(Time = as.numeric(difftime(Date,min(Date),units = "days")))

splitted.data <- multisplit(rnd1, c("Rep"))

dat <- splitted.data[[1]]
dat <- dat %>%
  mutate(Time = as.numeric(difftime(Date,min(Date),units = "days")))
fit <- fit_easylinear(dat$Time, dat$RFU)
summary(fit)
coef(fit) # exponential growth parameters
rsquared(fit)  # coefficient of determination (of log-transformed data)
deviance(fit)  # residual sum of squares of log-transformed data
par(mfrow = c(1, 2))
plot(fit, log = "y")
plot(fit)
```

```{r}
fitx <- fit_easylinear(dat$Time, dat$RFU, h = 8, quota = 0.95)
plot(fit, log = "y")
lines(fitx, pch = "+", col = "blue")
```


```{r}
all<- all_easylinear(RFU~Time | Rep, data = rnd1, h=6, quota = 1 )
```


```{r}
par(mfrow = c(1,3))
par(mar= c(1,1,1,1))
plot(all, log="y")
```


```{r}
res<- results(all)

res
```
## Growth rates for Round 3 (S.T. 1) LL

```{r}
library(ggplot2)
library(dplyr)
ammonium_trial %>% filter(Round == "3", Culture == "S.T. 1 from LL 7/23" ) %>% ggplot(aes(x = Date, y = RFU, color = Culture, shape = factor (Round)) ) +
  geom_point () +
  theme_test () +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_shape_manual(values = c(16)) +
  ggtitle(expression("Pyrodinium growth with " * NH[4]^"+" * " addition and " * NO[3]^"-" * " elimination"))

```

```{r}
library(growthrates)
rnd1 <- ammonium_trial %>% filter(Round == "3", Culture == "S.T. 1 from LL 7/23" ) %>%
  mutate(Time = as.numeric(difftime(Date,min(Date),units = "days")))

splitted.data <- multisplit(rnd1, c("Rep"))

dat <- splitted.data[[1]]
dat <- dat %>%
  mutate(Time = as.numeric(difftime(Date,min(Date),units = "days")))
fit <- fit_easylinear(dat$Time, dat$RFU)
summary(fit)
coef(fit) # exponential growth parameters
rsquared(fit)  # coefficient of determination (of log-transformed data)
deviance(fit)  # residual sum of squares of log-transformed data
par(mfrow = c(1, 2))
plot(fit, log = "y")
plot(fit)
```

```{r}
fitx <- fit_easylinear(dat$Time, dat$RFU, h = 8, quota = 0.95)
plot(fit, log = "y")
lines(fitx, pch = "+", col = "blue")
```


```{r}
all<- all_easylinear(RFU~Time | Rep, data = rnd1, h=6, quota = 1 )
```


```{r}
par(mfrow = c(1,3))
par(mar= c(1,1,1,1))
plot(all, log="y")
```


```{r}
res<- results(all)

res
```

## Growth rates for Round 1 OTB

```{r}
library(ggplot2)
library(dplyr)
ammonium_trial %>% filter(Round == "1", Culture == "OTB_1006 6/10" ) %>% ggplot(aes(x = Date, y = RFU, color = Culture, shape = factor (Round)) ) +
  geom_point () +
  theme_test () +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_shape_manual(values = c(16)) +
  ggtitle(expression("Pyrodinium growth with " * NH[4]^"+" * " addition and " * NO[3]^"-" * " elimination"))

```

```{r}
library(growthrates)
rnd1 <- ammonium_trial %>% filter(Round == "1", Culture == "OTB_1006 6/10" ) %>%
  mutate(Time = as.numeric(difftime(Date,min(Date),units = "days")))

splitted.data <- multisplit(rnd1, c("Rep"))

dat <- splitted.data[[1]]
dat <- dat %>%
  mutate(Time = as.numeric(difftime(Date,min(Date),units = "days")))
fit <- fit_easylinear(dat$Time, dat$RFU)
summary(fit)
coef(fit) # exponential growth parameters
rsquared(fit)  # coefficient of determination (of log-transformed data)
deviance(fit)  # residual sum of squares of log-transformed data
par(mfrow = c(1, 2))
plot(fit, log = "y")
plot(fit)
```

```{r}
fitx <- fit_easylinear(dat$Time, dat$RFU, h = 8, quota = 0.95)
plot(fit, log = "y")
lines(fitx, pch = "+", col = "blue")
```


```{r}
all<- all_easylinear(RFU~Time | Rep, data = rnd1, h=10, quota = 1 )
```


```{r}
par(mfrow = c(1,3))
par(mar= c(1,1,1,1))
plot(all, log="y")
```


```{r}
res<- results(all)

res
```

## Growth rates for Round 3 (S.T. 1) OTB

```{r}
library(ggplot2)
library(dplyr)
ammonium_trial %>% filter(Round == "3", Culture == "S.T. 1 from OTB 6/10" ) %>% ggplot(aes(x = Date, y = RFU, color = Culture, shape = factor (Round)) ) +
  geom_point () +
  theme_test () +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_shape_manual(values = c(16)) +
  ggtitle(expression("Pyrodinium growth with " * NH[4]^"+" * " addition and " * NO[3]^"-" * " elimination"))

```

```{r}
library(growthrates)
rnd1 <- ammonium_trial %>% filter(Round == "3", Culture == "S.T. 1 from OTB 6/10" ) %>%
  mutate(Time = as.numeric(difftime(Date,min(Date),units = "days")))

splitted.data <- multisplit(rnd1, c("Rep"))

dat <- splitted.data[[1]]
dat <- dat %>%
  mutate(Time = as.numeric(difftime(Date,min(Date),units = "days")))
fit <- fit_easylinear(dat$Time, dat$RFU)
summary(fit)
coef(fit) # exponential growth parameters
rsquared(fit)  # coefficient of determination (of log-transformed data)
deviance(fit)  # residual sum of squares of log-transformed data
par(mfrow = c(1, 2))
plot(fit, log = "y")
plot(fit)
```

```{r}
fitx <- fit_easylinear(dat$Time, dat$RFU, h = 8, quota = 0.95)
plot(fit, log = "y")
lines(fitx, pch = "+", col = "blue")
```


```{r}
all<- all_easylinear(RFU~Time | Rep, data = rnd1, h=6, quota = 1 )
```


```{r}
par(mfrow = c(1,3))
par(mar= c(1,1,1,1))
plot(all, log="y")
```


```{r}
res<- results(all)

res

```

## Rbind
 
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

# Define %ni% operator if not already defined
`%ni%` <- Negate(`%in%`)

amm <- ammonium_trial %>% 
  filter(Round %in% c(1, 3, 4, 5)) %>% 
  separate(Culture, into = c("bact"), sep = "_", remove = FALSE) %>%
  separate(bact, into = c("x", "y", "z", "bact1"), sep = " ", remove = FALSE) %>% 
  mutate(
    bact1 = case_when(
      bact %in% c("LL", "OTB") ~ bact,
      bact %ni% c("LL", "OTB") ~ bact1
    )
  )

# Plotting RFU by Day, colored by bact1, faceted by Round
amm %>% 
  ggplot(aes(x = Day, y = RFU, color = bact1)) + 
  geom_point(alpha = 0.8) + 
  theme_test() + 
  facet_grid(~Round) + 
  scale_color_manual(values = c("cornflowerblue", "gold")) + 
  geom_smooth(se = FALSE)
```


```{r}
# Filter for specific subset
gr_LL_rd1 <- amm %>%
  filter(bact1 == "LL", N == "NH4", Round == 1, Rep == 1) %>%
  mutate(mumax = 0.1677532) %>% 
  as.data.frame()

# Add Round column explicitly (optional, since Round should already be there)
gr_LL_rd1$Round <- 1

# Calculate summary stats grouped by bact1, N, Round, Rep (using filtered data)
mean_res1 <- gr_LL_rd1 %>%
  group_by(bact1, N, Round, Rep) %>%
  summarize(
    mean_gr = mean(mumax, na.rm = TRUE),
    sd = sd(mumax, na.rm = TRUE),
    .groups = "drop"
  )
```


```{r}
library(dplyr)

df1_text <- "
bact1, N, Round, Rep, mumax
LL, NH4, 1, 1, 0.1677532
LL, NH4, 1, 2, 0.1552915
LL, NH4, 1, 3, 0.1754041
LL, NH4, 3, 1, 0.2494516
LL, NH4, 3, 2, 0.2207191
LL, NH4, 3, 3, 0.2149846
OTB, NH4, 1, 1, 0.09253599
OTB, NH4, 1, 2, 0.08705956
OTB, NH4, 1, 3, 0.10212820
OTB, NH4, 3, 1, 0.2416831
OTB, NH4, 3, 2, 0.1819155
OTB, NH4, 3, 3, 0.2065674
"

df1 <- read.csv(text = df1_text, stringsAsFactors = FALSE)

df1 <- df1 %>%
  mutate(ID = paste(bact1, N, Round, Rep, sep = "_"))

print(df1)


# Maggi gr 


df2_text <- "
Isolate,Nitrogen,Rep,Transfer,ID,mumax,r2
OTB,NO3,1,1,OTB_NO3_1_1,0.114120395408565,0.68976463365446
LD,NO3,1,1,LD_NO3_1_1,0.0933373154550199,0.575799428132732
OTB,NO3,2,1,OTB_NO3_1_2,0.16020914804909,0.851748240175957
LD,NO3,2,1,LD_NO3_1_2,0.0717797175865913,0.51825399128368
OTB,NO3,3,1,OTB_NO3_1_3,0.189612813415725,0.951462120451673
LD,NO3,3,1,LD_NO3_1_3,0.0975980555917156,0.642897908231712
OTB,NO3,1,2,OTB_NO3_2_1,0.271391985872395,0.790701231589318
LD,NO3,1,2,LD_NO3_2_1,0.153628701555169,0.698985490602533
OTB,NO3,2,2,OTB_NO3_2_2,0.202661517208214,0.916823000149281
LD,NO3,2,2,LD_NO3_2_2,0.27895462907155,0.936519134772629
OTB,NO3,3,2,OTB_NO3_2_3,0.252178631084456,0.831824949836659
LD,NO3,3,2,LD_NO3_2_3,0.142344675282164,0.733576150157809
"
# Read df2 from text
df2 <- read.csv(text = df2_text)

# Clean and align df2 AFTER renaming



df2_clean <- df2 %>%
  rename(
    bact1 = Isolate,
    N = Nitrogen
  ) %>%
  mutate(
    Round = Transfer,  # If Round is equivalent to Transfer
    ID = paste(bact1, N, Round, Rep, sep = "_")
  ) %>%
  select(bact1, N, Rep, Transfer, Round, ID, mumax)
df2_clean <- df2_clean %>%
  mutate(bact1 = ifelse(bact1 == "LD", "LL", bact1))
df2_clean <- df2_clean %>%
  mutate(ID = paste(bact1, N, Round, Rep, sep = "_"))


df2_clean <- df2 %>%
  rename(
    bact1 = Isolate,
    N = Nitrogen
  ) %>%
  select(bact1, N, Rep, Transfer, ID, mumax)

# First make sure both df1 and df2_clean have the same columns
df1 <- df1 %>%
  mutate(Transfer = Round) %>%
  select(bact1, N, Rep, Transfer, Round, ID, mumax)

# Combine NH4 and NO3 data
combined_df <- bind_rows(df1, df2_clean)

combined_df <- combined_df %>%
  mutate(bact1 = ifelse(bact1 == "LD", "LL", bact1))

```
## GR Box plot
```{r}
library(ggplot2)

ggplot(combined_df, aes(x = N, y = mumax, fill = bact1)) +
  geom_boxplot(alpha = 0.7, outlier.shape = NA, width = 0.6) +
  geom_jitter(aes(color = bact1), width = 0.2, size = 2, alpha = 0.6) +
  labs(
    title = "Growth rate (μmax) by Nitrogen Type and Isolate",
    x = "Nitrogen Source",
    y = "Growth Rate (μmax)",
    fill = "Isolate",
    color = "Isolate"
  ) +
  theme_minimal(base_size = 14)

table(combined_df$bact1, combined_df$N)

```


```{r}
library(dplyr)
library(ggplot2)

# --- Clean df1: already has Round = 1 or 3 (NH4) ---
df1 <- df1 %>%
  mutate(
    Round = case_when(
      Round == 1 ~ 1,
      Round == 3 ~ 2
    ),
    Transfer = Round,
    N = trimws(as.character(N))  # Remove extra spaces
  ) %>%
  select(bact1, N, Rep, Transfer, Round, ID, mumax)

# --- Clean df2: Transfer == 1 or 2 (NO3) ---
df2_clean <- df2 %>%
  rename(
    bact1 = Isolate,
    N = Nitrogen
  ) %>%
  mutate(
    Round = case_when(
      Transfer == 1 ~ 1,
      Transfer == 2 ~ 2  
    ),
    bact1 = ifelse(bact1 == "LD", "LL", bact1),
    ID = paste(bact1, N, Round, Rep, sep = "_"),
    N = trimws(as.character(N))  # Remove extra spaces
  ) %>%
  select(bact1, N, Rep, Transfer, Round, ID, mumax)

# --- Combine both datasets ---
combined_df <- bind_rows(df1, df2_clean)

# --- Plot ---
ggplot(combined_df, aes(x = N, y = mumax, fill = bact1)) +
  geom_boxplot(alpha = 0.7, outlier.shape = NA, width = 0.6) +
  geom_jitter(aes(color = bact1), width = 0.2, size = 2, alpha = 0.6) +
  labs(
    title = "Growth rate by Nitrogen Type and Isolate",
    x = "Nitrogen Source",
    y = "Growth Rate (μmax)",
    fill = "Isolate",
    color = "Isolate"
  ) +
  facet_grid(~Transfer) +
  scale_x_discrete(labels = c(
    "NO3" = expression(NO[3]),
    "NH4" = expression(NH[4])
  )) +
  scale_fill_manual(values = c("gold", "purple")) +
  scale_color_manual(values = c("gold", "purple")) +
  theme_test(base_size = 14)

```
ggsave("updated_NH4_NO3_boxplot.jpg", width = 7, height = 6)

## 34°C Trial
```{r import_packages, warning=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(purrr)
"%ni%" <- Negate("%in%")
library(googlesheets4)
library(patchwork)
```

```{r}
hottrial<- read_sheet("https://docs.google.com/spreadsheets/d/18_2ZNyk1GvUCoxckpurD9vz5-bD_RSRSeCNKY0YZf04/edit?usp=sharing")
```
```{r}
hottrial$Date <- ymd(hottrial$Date)
hottrial$Rep <- as.character(hottrial$Rep)
hottrial$RFU <- as.numeric(hottrial$RFU)
```

```{r}
hottrial %>%
  filter(Round %in% c(2, 3, 4)) %>%
  mutate(Round_label = case_when(
    Round == 2 ~ "Round 1 in 30°C",
    Round == 3 ~ "S.T. 1",
    Round == 4 ~ "S.T. 2",
  )) %>%
  ggplot(aes(x = Date, y = RFU, color = Culture)) +
  geom_point() +
  theme_test() +
  ggtitle("Pyrodinium growth in 30°C") +
  facet_grid(~ Round_label, scales = "free_x")

  
```
ggsave("hotonestrial_1015.jpg", width = 7, height = 6)


